### ISSUE TITLE
Script and output in different repos

### ISSUE THREAD

**Issue by bubbletroubles** [JulianHayward/AzADServicePrincipalInsights#4]
We are looking to run this in Azure DevOps pipelines and need to have the script in one repo (which the build service account has read-only access to), and the output in another repo (which the build service account has modify access to).

> (background to this is the "Limit Job authorisation scope" needs to be disabled on this DevOps project due to cross-project calls in other pipelines. This means that anyone who can run code on a build agent can write to the output repo. If the "script" repo and "output" repo are the same, then someone could overwrite the AzADServicePrincipalInsights script with new content which executes under the service connection (elevation of privilege, lateral movement etc).
![image](https://user-images.githubusercontent.com/42738824/160692917-e972d556-2dbf-4591-9163-e24df75d4625.png)

The script seems to have two incompatible references. As we have 2 x repos referenced in the pipeline .yaml file

``` yaml
resources:
  repositories:
  - repository: scripts
    type: git
    name: ProjectName/Governance-Scripts
    ref: main
  - repository: output
    type: git
    name: ProjectName/Governance-Output
    ref: main
```
We then need to update the scriptPath variables as below
``` yaml
variables:
  WikiDir: Governance-Output/AzADServicePrincipalInsights # Note: Prefixed with repo reference https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
  ScriptDir: Governance-Scripts/AzADServicePrincipalInsights/pwsh # Note: Prefixed with repo reference https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
```
We then get this error
```
Get-Content: /home/vsts/work/1/s/Governance-Scripts/AzADServicePrincipalInsights/pwsh/AzADServicePrincipalInsights.ps1:3465
Line |
3465 |  … fications = Get-Content -raw .\pwsh\permissionClassification.json | C …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/vsts/work/1/s/pwsh/permissionClassification.json'
     | because it does not exist.

```

If we then set the workingDirectory on the Powershell task as below

``` yaml
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: '$(ServiceConnection)'
      scriptType: filePath
      pwsh: true
      scriptPath: '$(System.DefaultWorkingDirectory)/$(ScriptDir)/$(Script)'
      scriptArguments: '-OutputPath $(WikiDir)'
      azurePowerShellVersion: latestVersion
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(ScriptDir)'
    displayName: 'Run AzADServicePrincipalInsights v1'
```

We then get another error

```
path /home/vsts/work/1/s/Governance-Scripts/AzADServicePrincipalInsights/pwsh/Governance-Scripts/AzADServicePrincipalInsights/. does not exist - please create it!
Exception: /home/vsts/work/1/s/Governance-Scripts/AzADServicePrincipalInsights/pwsh/AzADServicePrincipalInsights.ps1:104
Line |
 104 |          Throw 'Error - check the last console output for details'
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details
```

Any ideas?

**Comment by JulianHayward** [comment]
can you please provide a working sample yml where you clone from the source repository, create outputs and then push to a second repository?

**Comment by bubbletroubles** [comment]
We use the config with AzGovViz and this is the working YAML pipeline for AzGovViz. We didn't have to make any changes to the AzGovViz powershell itself.

the main customsiations were

- Addition of an OutputRepo variable
- Addition of 2 x repo resources
- Change the  working directory using `cd AzGovViz-Scripts`
- Update $PipelineInfo parameter (Repository: $(OutputRepoName) )

````
# AzGovViz v6_major_20211018_1
# First things first: 
# 1. edit line 59 and line 60 
# 2. check line 74 and 85 if branch 'master' is applicable 
# Documentation: https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting
# Also check https://www.azadvertizer.net - AzAdvertizer helps you to keep up with the pace by providing overview and insights on new releases and changes/updates for Azure Governance capabilities such as Azure Policy's policy definitions, initiatives (set definitions), aliases and Azure RBAC's role definitions and resource provider operations.
# 
# Parameters reference (use in line 108)
# LimitCriticalPercentage | default is '80' | example: -LimitCriticalPercentage 90  | WhatDoesItDo? marks capabilities that approch limits e.g. limit 100, usage 80 will mark with warning
# SubscriptionQuotaIdWhitelist | default is 'undefined' | example: -SubscriptionQuotaIdWhitelist MSDN_, EnterpriseAgreement_ | WhatDoesItDo? processes only Subscriptions that startWith the given QuotaIds
# HierarchyMapOnly | switch | example: -HierarchyMapOnly | WhatDoesItDo? only creates the Hierarchy Tree
# DoNotShowRoleAssignmentsUserData | switch | example: -DoNotShowRoleAssignmentsUserData | WhatDoesItDo? scrub user information
# NoASCSecureScore | switch | example: -NoASCSecureScore | WhatDoesItDo? disables ASC Secure Score request for Subscriptions and Management Groups
# CsvDelimiter | example: -CsvDelimiter "," | WhatDoesItDo? the world is split into two kind of delimiters - comma and semicolon - choose yours
# NoPolicyComplianceStates | example: -NoPolicyComplianceStates | WhatDoesItDo? will not query policy compliance states
# NoResourceDiagnosticsPolicyLifecycle | example: -NoResourceDiagnosticsPolicyLifecycle | WhatDoesItDo? will not create Resource Diagnostics Policy Lifecycle recommendations
# NoAADGroupsResolveMembers | example: -NoAADGroupsResolveMembers | WhatDoesItDo? will not resolve Azure Active Directory Group memberships for Role assignments where identity type is 'Group'
# AADServicePrincipalExpiryWarningDays | example: -AADServicePrincipalExpiryWarningDays 21 | WhatDoesItDo? define warning period for Service Principal secret and certificate expiry; default is 14 days
# NoAzureConsumption | example: -NoAzureConsumption | WhatDoesItDo? Azure Consumption data will not be collected/reported
# AzureConsumptionPeriod | example: -AzureConsumptionPeriod 7 | WhatDoesItDo? define for which time period Azure Consumption data should be gathered; default is 1 day
# NoAzureConsumptionReportExportToCSV | example: -NoAzureConsumptionReportExportToCSV | WhatDoesItDo? Azure Consumption data will not be exported (CSV)
# ThrottleLimit | example: -ThrottleLimit 10 | WhatDoesItDo? Define the number of script blocks running in parallel. Leveraging PowerShell Core´s parallel capability you can define the ThrottleLimit (default=5)
# DoTranscript | example: -DoTranscript | WhatDoesItDo? Log the console output
# AzureDevOpsWikiHierarchyDirection | example: -AzureDevOpsWikiHierarchyDirection "LR" | WhatDoesItDo? Define the direction the Hierarchy should be built in Azure DevOps WokiAsCode (Markdown) TD = TopDown (Horizontal), LR = LeftRight (Vertical)
# SubscriptionId4AzContext | example: -SubscriptionId4AzContext "<your-Subscription-Id>" | WhatDoesItDo? Define the Subscription Id to use for AzContext (default is to use a random Subscription Id)
# NoCsvExport | example: -NoCsvExport | WhatDoesItDo? Do not export enriched 'Role assignments' data, enriched 'Policy assignments' data and 'all resources' (subscriptionId, resourceType, id, name, location, tags, createdTime, changedTime)
# DoNotIncludeResourceGroupsOnPolicy | example: -DoNotIncludeResourceGroupsOnPolicy | WhatDoesItDo? Do not include Policy assignments on ResourceGroups
# DoNotIncludeResourceGroupsAndResourcesOnRBAC | example: -DoNotIncludeResourceGroupsAndResourcesOnRBAC | WhatDoesItDo? Do not include Role assignments on ResourceGroups and Resources
# ChangeTrackingDays | example: -ChangeTrackingDays 30 | WhatDoesItDo? Tracks newly created and updated custom Policy, PolicySet and RBAC Role definitions, Policy/RBAC Role assignments and Resources that occured within the last 14 days (default)
# FileTimeStampFormat | example: -FileTimeStampFormat "yyyyMM-dd_HHmm" | WhatDoesItDo? Time format for the output files (default is `yyyyMMdd_HHmmss`)
# NoJsonExport | example: -NoJsonExport | WhatDoesItDo? Do not export of ManagementGroup Hierarchy including all MG/Sub Policy/RBAC definitions, Policy/RBAC assignments and some more relevant information to JSON
# JsonExportExcludeResourceGroups | example: -JsonExportExcludeResourceGroups | WhatDoesItDo?| JSON Export will not include ResourceGroups (Policy & Role assignments)
# JsonExportExcludeResources | example: -JsonExportExcludeResources | WhatDoesItDo?| JSON Export will not include Resources (Role assignments)
# LargeTenant | example: -LargeTenant | WhatDoesItDo? A large tenant is a tenant with more than ~500 Subscriptions - the HTML output for large tenants simply becomes too big. If the parameter switch is true then the following parameters will be set: -PolicyAtScopeOnly $true, -RBACAtScopeOnly $true, -NoResourceProvidersDetailed $true, -NoScopeInsights $true
# PolicyAtScopeOnly | example: -PolicyAtScopeOnly | WhatDoesItDo? Removing 'inherited' lines in the HTML file for 'Policy Assignments'; use this parameter if you run against a larger tenants
# RBACAtScopeOnly | example: -RBACAtScopeOnly | WhatDoesItDo? Removing 'inherited' lines in the HTML file for 'Role Assignments'; use this parameter if you run against a larger tenants
# NoResourceProvidersDetailed | switch | example: -NoResourceProvidersDetailed | WhatDoesItDo? disables 'ResourceProvider Detailed' output for TenantSummary (compute intensive)
# NoScopeInsights | example: -NoScopeInsights | WhatDoesItDo? and why would you want to do this? In larger tenants the ScopeInsights section blows up the html file (up to unusable due to html file size). To further reduce the output use parameter -LargeTenant
# HtmlTableRowsLimit | example: -HtmlTableRowsLimit | WhatDoesItDo? Although the parameter -LargeTenant was introduced recently, still the html output may become too large to be processed properly. The new parameter defines the limit of rows - if for the html processing part the limit is reached then the html table will not be created (csv and json output will still be created). Default rows limit is 40.000
# AADGroupMembersLimit | example: -AADGroupMembersLimit 333 | WhatDoesItDo? Defines the limit (default=500) of AAD Group members; For AAD Groups that have more members than the defined limit Group members will not be resolved
# NoResources | example: -NoResources | WhatDoesItDo? Will speed up the processing time but information like Resource diagnostics capability and resource type stats (featured for large tenants)
# StatsOptOut | example: -StatsOptOut | WhatDoesItDo? Will opt-out sending stats

trigger: none

pr: none

parameters:
- name: exludedResourceTypesDiagnosticsCapableParameters
  type: object
  default:
    - microsoft.web/certificates
- name: subscriptionQuotaIdWhitelistParameters
  type: object
  default:
    - Enterprise,MSDNDevTest,PayAsYouGo

variables:
  ServiceConnection: AzGovViz #permissions set? https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting#required-permissions-in-azure 
  ManagementGroupId: xxxx-xxxx-xxxx-xxxx-xxxx
  SubscriptionQuotaIdWhitelist: ${{ join(',',parameters.subscriptionQuotaIdWhitelistParameters) }}
  ExludedResourceTypesDiagnosticsCapable: ${{ join(',',parameters.exludedResourceTypesDiagnosticsCapableParameters) }}
  WikiDir: AzGovViz-Output/wiki/tenant-name # Note: Prefixed with repo reference https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
  CsvDelimiter: ;
  ScriptDir: AzGovViz-Scripts/AzGovViz/pwsh # Note: Prefixed with repo reference https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
  Script: AzGovVizParallel.ps1
  OutputRepoName: AzGovViz-Output

schedules:
- cron: "0 0,12 * * *"
  displayName: every 12h
  always: true
  branches:
    include:
    - main #CHECK: branch 'master' is applicable? - delete me :)

resources:
  repositories:
  - repository: scripts
    type: git
    name: Project-Name/AzGovViz-Scripts
    ref: main
  - repository: output
    type: git
    name: Project-Name/AzGovViz-Output
    ref: main

jobs:
- job: AzGovViz  
  timeoutInMinutes: 0

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: self
  - checkout: output
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/$(ScriptDir)/prerequisites.ps1
    displayName: 'Prerequisites check'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: '$(ServiceConnection)'
      scriptType: filePath
      pwsh: true
      scriptPath: '$(System.DefaultWorkingDirectory)/$(ScriptDir)/$(Script)'
      scriptArguments: '-ManagementGroupId $(ManagementGroupId) -OutputPath $(WikiDir) -CsvDelimiter "$(CsvDelimiter)" -AzureDevOpsWikiAsCode -SubscriptionQuotaIdWhitelist $(SubscriptionQuotaIdWhitelist) -ExludedResourceTypesDiagnosticsCapable $(ExludedResourceTypesDiagnosticsCapable) -StatsOptOut'
      azurePowerShellVersion: latestVersion
    displayName: 'Run AzGovViz v6'
  - powershell: |
      write-host "#################################"
      write-host "Push AzGovViz output to repository"
      write-host "#################################"
      pwd
      cd AzGovViz-Scripts
      $executionDateTimeInternationalReadable = get-date -format "dd-MMM-yyyy HH:mm:ss"
      $currentTimeZone = (Get-TimeZone).Id
      git config --global user.email "AzGovVizPipeline@domain.com"
      $PipelineInfo = "Pipeline: '$(Build.DefinitionName)' 'rev $(Build.BuildNumber)' (Project: $([uri]::EscapeDataString("$(System.TeamProject)")); Repository: $(OutputRepoName) ; Branch: $(Build.SourceBranchName) Commit: $(Build.SourceVersion))"
      git config --global user.name "$PipelineInfo"
      git config pull.rebase false
      write-host "Running git add"
      git add --all
      write-host "Running git commit"
      git commit -m "wiki $executionDateTimeInternationalReadable ($currentTimeZone)"
      write-host "Running git push"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:main
    displayName: 'Push AzGovViz v6 output to repository'
````
